name: Zephyr West
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: |
          sudo apt update
          sudo apt upgrade
          wget https://apt.kitware.com/kitware-archive.sh
          sudo bash kitware-archive.sh
      - name: dependencies
        run: |
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
      - name: python
        run: |
          sudo apt install python3-venv
          python3 -m venv ~/zephyrproject/.venv
          source ~/zephyrproject/.venv/bin/activate
          pip install west
          west init ~/zephyrproject
          cd ~/zephyrproject
          west update
          west zephyr-export
          pip install -r ~/zephyrproject/zephyr/scripts/requirements.txt

